final

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,25 +37,25 @@ jobs:
           keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
           keyPassword: ${{ secrets.KEY_PASSWORD }}
 
-      - name: Clean up build artifacts
-        run: |
-          set -e
+      # - name: Clean up build artifacts
+      #   run: |
+      #     set -e
 
-          mv build/app/outputs/flutter-apk/app-release-signed.apk chuck-api.apk
-          sha=`sha256sum chuck-api.apk | awk '{ print $1 }'`
-          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
+      #     mv build/app/outputs/flutter-apk/app-release-signed.apk chuck-api.apk
+      #     sha=`sha256sum chuck-api.apk | awk '{ print $1 }'`
+      #     echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
 
-          cp build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk chuck-api-arm64-v8a.apk
-          sha=`sha256sum chuck-api-arm64-v8a.apk | awk '{ print $1 }'`
-          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk chuck-api-arm64-v8a.apk
+      #     sha=`sha256sum chuck-api-arm64-v8a.apk | awk '{ print $1 }'`
+      #     echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
 
-          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release-signed.apk chuck-api-armeabi-v7a.apk
-          sha=`sha256sum chuck-api-armeabi-v7a.apk | awk '{ print $1 }'`
-          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/flutter-apk/app-armeabi-v7a-release-signed.apk chuck-api-armeabi-v7a.apk
+      #     sha=`sha256sum chuck-api-armeabi-v7a.apk | awk '{ print $1 }'`
+      #     echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
 
-          cp build/app/outputs/flutter-apk/app-x86_64-release-signed.apk chuck-api-x86.apk
-          sha=`sha256sum chuck-api-x86.apk | awk '{ print $1 }'`
-          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/flutter-apk/app-x86_64-release-signed.apk chuck-api-x86.apk
+      #     sha=`sha256sum chuck-api-x86.apk | awk '{ print $1 }'`
+      #     echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
 
       - name: Create Release
         uses: softprops/action-gh-release@v1
@@ -72,10 +72,10 @@ jobs:
             | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
             | x86 | ${{ env.APK_X86_SHA }} |
           files: |
-            chuck-api-release-signed.apk
-            chuck-api-arm64-v8a-release-signed.apk
-            chuck-api-armeabi-v7a-release-signed.apk
-            chuck-api-x86-release-signed.apk
+            app-release-signed.apk
+            app-arm64-v8a-release-signed.apk
+            app-armeabi-v7a-release-signed.apk
+            app-x86-release-signed.apk
           draft: false
           prerelease: false
         env:
