finnnnal

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,29 +23,9 @@ jobs:
           flutter-version: '2.10.4'
       - run: flutter pub get
       - run: flutter test
-      - run: flutter build apk --split-per-abi
+      - name: Build Apk
+        run: flutter build apk --release --split-per-abi --build-number=${GITHUB_RUN_NUMBER}
 
-      # - name: Sign APK
-      #   uses: r0adkll/sign-android-release@v1
-      #   with:
-      #     releaseDirectory: build/app/outputs/apk/release
-      #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
-      #     alias: ${{ secrets.ALIAS }}
-      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
-      #     keyPassword: ${{ secrets.KEY_PASSWORD }}
-
-      # - uses: ncipollo/release-action@v1
-      #   with:
-      #     artifacts: "build/app/outputs/apk/release/*"
-      #     tag: v1.0.${{ github.run_number }}
-      #     token: ${{ secrets.TOKEN }}
-
-
-
-      - name: Get tag name
-        run: |
-          set -x
-          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
       - name: Sign APK
         uses: r0adkll/sign-android-release@v1
         with:
@@ -55,42 +35,63 @@ jobs:
           keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
           keyPassword: ${{ secrets.KEY_PASSWORD }}
 
-      - name: Clean up build artifacts
-        run: |
-          set -e
-          mv build/app/outputs/apk/release/app-universal-release-unsigned-signed.apk chuck-api-${{ env.VERSION_TAG }}.apk
-          sha=`sha256sum chuck-api-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
-          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
-          cp build/app/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk
-          sha=`sha256sum chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
-          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
-          cp build/app/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk
-          sha=`sha256sum chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
-          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
-          cp build/app/outputs/apk/release/app-x86-release-unsigned-signed.apk chuck-api-x86-${{ env.VERSION_TAG }}.apk
-          sha=`sha256sum chuck-api-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
-          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
-
-      - name: Create Release
-        uses: softprops/action-gh-release@v1
+      - uses: ncipollo/release-action@v1
         with:
-          tag_name: ${{ env.VERSION_TAG }}
-          name: Tachiyomi ${{ env.VERSION_TAG }}
-          body: |
-            ---
-            ### Checksums
-            | Variant | SHA-256 |
-            | ------- | ------- |
-            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
-            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
-            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
-            | x86 | ${{ env.APK_X86_SHA }} |
-          files: |
-            chuck-api-${{ env.VERSION_TAG }}.apk
-            chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk
-            chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk
-            chuck-api-x86-${{ env.VERSION_TAG }}.apk
-          draft: true
-          prerelease: false
-        env:
-          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+          artifacts: "build/app/outputs/apk/release/*"
+          tag: v1.0.${{ github.run_number }}
+          token: ${{ secrets.TOKEN }}
+
+
+
+      # - name: Get tag name
+      #   run: |
+      #     set -x
+      #     echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+      # - name: Sign APK
+      #   uses: r0adkll/sign-android-release@v1
+      #   with:
+      #     releaseDirectory: build/app/outputs/apk/release
+      #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
+      #     alias: ${{ secrets.ALIAS }}
+      #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
+      #     keyPassword: ${{ secrets.KEY_PASSWORD }}
+
+      # - name: Clean up build artifacts
+      #   run: |
+      #     set -e
+      #     mv build/app/outputs/apk/release/app-universal-release-unsigned-signed.apk chuck-api-${{ env.VERSION_TAG }}.apk
+      #     sha=`sha256sum chuck-api-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
+      #     echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk
+      #     sha=`sha256sum chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
+      #     echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk
+      #     sha=`sha256sum chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
+      #     echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
+      #     cp build/app/outputs/apk/release/app-x86-release-unsigned-signed.apk chuck-api-x86-${{ env.VERSION_TAG }}.apk
+      #     sha=`sha256sum chuck-api-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
+      #     echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
+
+      # - name: Create Release
+      #   uses: softprops/action-gh-release@v1
+      #   with:
+      #     tag_name: ${{ env.VERSION_TAG }}
+      #     name: Tachiyomi ${{ env.VERSION_TAG }}
+      #     body: |
+      #       ---
+      #       ### Checksums
+      #       | Variant | SHA-256 |
+      #       | ------- | ------- |
+      #       | Universal | ${{ env.APK_UNIVERSAL_SHA }}
+      #       | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
+      #       | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
+      #       | x86 | ${{ env.APK_X86_SHA }} |
+      #     files: |
+      #       chuck-api-${{ env.VERSION_TAG }}.apk
+      #       chuck-api-arm64-v8a-${{ env.VERSION_TAG }}.apk
+      #       chuck-api-armeabi-v7a-${{ env.VERSION_TAG }}.apk
+      #       chuck-api-x86-${{ env.VERSION_TAG }}.apk
+      #     draft: true
+      #     prerelease: false
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
